config/routes.rb
Rails.application.routes.draw do
  get 'orders/bought'
  get 'orders/sold'
  resources :listings
  devise_for :users
  root 'pages#home'

  post "listings/:id/order", to: "listings#place_order", as: "place_order"

  get 'orders/success', to: 'orders#success', as:"order_success"
  get 'search', to: "listings#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :user
end

app/models/allergy.rb
class Allergy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :allergy
  has_rich_text :description
  has_one_attached :image

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "User"
  belongs_to :seller, foreign_key: "seller_id", class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
  belongs_to :address
  accepts_nested_attributes_for :address

  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :bought_orders, foreign_key: "buyer_id", class_name: "Order"

  def with_address
    build_address if address.nil?
    self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :username, :password, :password_confirmation, address_attributes: [:street_number, :street_name, :suburb, :postcode])
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy place_order]
  before_action :set_form_vars, only: %i[ new edit ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # GET search
  def search
    if params[:selected] == 'title'
    @listings = Listing.where("title ILIKE ?", "%" + params[:q] + "%")
    pp @listings
    elsif params[:selected] == 'suburb'
    @listings = Listing.joins(user:[:address]).where("suburb ILIKE ?", "%" + params[:q] + "%")
    end
  end

  # POST /listings or /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def place_order
      Order.create!(
      listing_id: @listing.id,
      seller_id: @listing.user_id,
      buyer_id: current_user.id
    )

    @listing.update(sold: true)

    redirect_to order_success_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def set_form_vars
      @allergies = Allergy.all
    end

    # method to check user who owns listing is the logged in user
    def authorize_user
      if @listing.user_id != current_user.id
        flash[:alert] = "we are unable to proceed with that action, please sign in"
        redirect_to listings_path
      end
    end


    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :cuisine, :description, :price, :available_date, :sold, :user_id, :allergy_id, :image)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  
  def success
  end

  def bought
    @bought_items = current_user.bought_orders
  end

  def sold
    @sold_items = current_user.sold_orders
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuna And Rice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>

</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :cuisine %>
    <%= form.text_field :cuisine %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :available_date %>
    <%= form.text_field :available_date %>
  </div>

   <div class="field">
    <%= form.label :allergy_id %>
    <%= form.select :allergy_id, @allergies.map {|a| [a.name, a.id]} %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, accept: "image/png, image/jpg, image/jpeg" %>
  </div>

  <p class="message"> <em> Note! Your listing will be posted with your profiles suburb and postcode </em> </p>

  <div class="actions">
    <%= form.submit%>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<%=image_tag('6.png', class:"hero-body")%></br>

<h1>Listings</h1>
<p id="notice"><%= notice %></p>

<div>
  <form action="/search">
    <input name= "q" type="text" placeholder="search" aria-label="search">
    <select name='selected'> <option value='title'> title </option> <option value='suburb'> suburb </option></select>
    <button type="submit">Search</button>
  </form>
</div>

<p style= "display:flex; justify-content:center; margin:10px;"><%= link_to 'Click here to post a new meal to sell or donate!', new_listing_path, class: "post-button" %></p></br>

<section>
  <%= render "shared/listingcard" %>
</section>
</br>

<%= render "shared/footer" %>

app/views/listings/new.html.erb
<p><%=image_tag('5.png', class:"hero-body")%><p></br>

<p class="message"> 👏 Thanks for getting involved with <em>Tuna and Rice</em>, your meal listing will help our community 👨‍👨‍👧‍👧</p>

<h1>New Listing</h1>


<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/search.erb
<h1>Search Results</h1>

<%= render "shared/listingcard" %>

app/views/listings/show.html.erb
<div class="card">

  <div>
    <%# user attaching image and if there is none attached %>
    <% if @listing.image.attached? %>
        <%= image_tag @listing.image, alt: @listing.title %>
    <% else %>
      <%=image_tag('loading.jpg')%>
    <% end %>
  </div>

    <div>
      <h3>
        <strong>Title:</strong>
        <%= @listing.title %>
      </h3>

      <h5>
        <strong>Cuisine:</strong>
        <%= @listing.cuisine %>
      </h5>

      <h5>
        <strong>Description:</strong>
        <%= @listing.description %>
      </h5>

      <h5>
        <strong>Price:</strong> $
        <%= @listing.price %>
      </h5>

      <h5>
        <strong>Available date:</strong>
        <%= @listing.available_date %>
      </h5>

      <h5>
        <strong>Allergies listed:</strong>
        <%= @listing.allergy.name %>
      </h5>

        <h5>
        <strong>Location for Pick Up:</strong>
          <%= @listing.user.address.suburb %>,
          <%= @listing.user.address.postcode %>
      </h5>

      <%# user not see options if they don't own the listing %>
      <% if current_user.id == @listing.user_id %>
          <%= link_to 'Edit this meals details!', edit_listing_path(@listing), class: "button button-primary" %>
      <% end %>
    </div>

    <div>
      <p id="notice"><%= notice %></p>

        <%# check if item sold, lists sold %>
        <% if @listing.sold %>
          <h3> This is meal has been claimed: </h3>
        <%# check if current user and that they aren't able to purchase own item %>
        <% elsif current_user && current_user.id == @listing.user_id %>
          <h3> You posted this meal! ...it's yet to be claimed </h3>
        <%# current user able to buy meal %>
        <% elsif current_user %>
        <%# buy button %>
          <%= button_to "Get the meal!", place_order_path %>
        <% else %>
          <p> Please sign in to claim a meal </p>
        <% end %>
    </div>
</div>

<%= link_to 'Back', listings_path %>

<%= render "shared/footer" %>

app/views/orders/bought.html.erb
<%=image_tag('3.png', class:"hero-body")%></br>

<h1> 👋 Hello <%= current_user.username%>!</h1>

<h3>Here are the meals that you have claimed 🌞 :</h3>

<div class="card">
  <body>
    <% @bought_items.each do |item| %>
      <div>
      <%# user attaching image and if there is none attached %>
        <% if item.listing.image.attached? %>
          <%= image_tag item.listing.image, alt: item.listing.title %>
        <% else %>
          <%=image_tag('loading.jpg')%>
        <% end %>
      </div>
      <span>
        <td><%= item.listing.title %></td>
        <td> Cusine:<%= item.listing.cuisine %></td>
        <td><%= item.listing.description %></td>
        <td> Allergies: <%= item.listing.allergy.name %></td>
        <td> Date Claimed:<%= item.listing.available_date %></td>
        <td> Price: $<%= item.listing.price %></td>
        <td> Bought from:<%= item.listing.user.username %></td>
        <h5> Location picked up: 
            <%= item.listing.user.address.street_number %>,
            <%= item.listing.user.address.street_name %>,
            <%= item.listing.user.address.suburb %>,
            <%= item.listing.user.address.postcode %></h5>
      </span>
    <% end %>
  </body>
</div>

app/views/orders/sold.html.erb
<%=image_tag('2.png', class:"hero-body")%></br>

<h1> 👋 Hello <%= current_user.username%>!</h1>

<%= link_to 'Click here to post a new meal to sell or donate!', new_listing_path, class: "post-button" %></br>


<h3>Here are the meals that you have <strong>sold or donated </strong>to your community 🧑‍🤝‍🧑 :</h3></br>

<div class="card">

  <body>
    <% @sold_items.each do |item| %>
      <div>
      <%# user attaching image and if there is none attached %>
        <% if item.listing.image.attached? %>
          <%= image_tag item.listing.image, alt: item.listing.title %>
        <% else %>
          <%=image_tag('loading.jpg')%>
        <% end %>
      </div>
      <span>
        <td><%= item.listing.title %></td>
        <td> Cusine:<%= item.listing.cuisine %></td>
        <td><%= item.listing.description %></td>
        <td> Allergies: <%= item.listing.allergy.name %></td>
        <td> Date Claimed:<%= item.listing.available_date %></td>
        <td> Price: $<%= item.listing.price %></td>
        <td> Bought by:<%= item.listing.user.username %></td>
        <h5> Location for picked up: 
            <%= item.listing.user.address.street_number %>,
            <%= item.listing.user.address.street_name %>,
            <%= item.listing.user.address.suburb %>,
            <%= item.listing.user.address.postcode %></h5>
      </span>
    <% end %>
  </body>
  </div>

<p class="message">Thanks for helping out!</p></br>

app/views/orders/success.html.erb
<%=image_tag('4.png', class:"hero-body")%></br>

<div style= "text-align:center">
    <h1> Your order has been placed! Please meet at the location listed on the meal on the date available! 🌞</h1>

    <h3 class="message"> see "My meals claimed" </h3>
</div>

app/views/pages/home.html.erb
<%=image_tag('mainlogo.png', class:"hero-body")%></br>

<div style= "text-align:center">
<h4> Tuna and Rice allows you <em>as a user</em> to help those in our community 🧑‍🤝‍🧑 who may be struggling.</h4></br>

<h5>We welcome you to sign up and post a meal to help someone who may be struggling to make ends meet this week!</h5>
<h5>These meals can be your leftover bowl from dinner, bread, pantry items, resturant leftovers or an entire basket of goodies!
These meals can be at cost but we do encourage donations/$0 meals at <em> Tuna and Rice </em></h5>

<h5>You can also sign up to claim a meal! 
Discover what meals are available near you through our handy search bar! Just enter the suburb or postcode.</h5><br>

<h5> <strong>We hope you make a small difference to your community here at <em> Tuna and Rice</em> </strong></h5></br>
</div>

<p class="message">Please checkout the meals we have available by clicking on <strong> Available Meals!</strong> ⬆️</p></br>

<h5 class="facts"><strong>
Lets Reduce Poverty!
Lets Reduce Wastage!</strong></h5></br>

<p class="facts">2020 report Poverty in Australia 2020: Part 1, Overview found that there are 3.24 million people
(13.6%) living below the poverty line of 50% of median income.In Australia the poverty line translates to a single adult living on less than $426.30 a week.</p></br>

<p class="facts">Two-thirds of university students living below the poverty line. one in five students occasionally go without food</p></br>

<p class="facts">
Universities Australia surveyed close to 12,000 full-time undergraduate and postgraduate students.
Twenty-one per cent of respondents had an annual income of less than $10,000, and a further 40.3
per cent earned between $10,000 and $19,000.
<a style = "color:#FF1493;" href="https://gupsa.org.au/two-thirds-of-university-students-living-below-the-poverty-line-report/#:~:text=Universities%20Australia%20surveyed%20close%20to,was%20%2418%2C634%20for%20undergraduate%20students."> Read more here! </a></p></br>

<p style= "display:flex; justify-content:center; margin:10px;"><%= link_to 'Click here to post a new meal to sell or donate!', new_listing_path, class: "post-button" %></p>

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<footer class="footer-text">
<%# logo on bottom left in footbar %>
    <%=image_tag('logo.png', class:"logo")%>
      <strong>Tuna and Rice &copy</strong> 2022 by Megan Van Der Weide.
</footer>

app/views/shared/_listingcard.erb
<div class="card">

  <body>
      <%# user attaching image and if there is none attached %>
    <% @listings.each do |listing| %>
      <div>
          <% if listing.image.attached? %>
              <%= image_tag listing.image, alt: listing.title %>
          <% else %>
            <%=image_tag('loading.jpg')%>
          <% end %>
        </div>

      <div>
        <h3><%= listing.title %></h3>
        <h5> Cusine: <%= listing.cuisine %> </h5>
        <h5><%= listing.description %></h5>
        <h5> Allergies: <%= listing.allergy.name %></h5>
        <h5> Date Available: <%= listing.available_date %></h5>
        <h5> Price: $<%= listing.price %></h5>
        <h5> Location for pickup: 
            <%= listing.user.address.suburb %>,
            <%= listing.user.address.postcode %></h5>
        <h2 ><%= link_to 'View this meal!', listing, class: "button button-primary"%></h2>
        <%# user see options of edit/destroy if they own the listing %>
        <% if current_user && current_user.id == listing.user_id %>
            <h2><%= link_to 'Edit', edit_listing_path(listing), class: "button" %></h2>
            <h2><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></h2>
        <% end %>
        <h2> ----------------------------</h2>
      </div>
    <% end %>
  </body>
</div>

app/views/shared/_listingtable.erb
<div class="card">

  <body>
      <%# user attaching image and if there is none attached %>
    <%# <div> %>
      <%# <% if @listing.image.attached? %> %>
          <%# <%= image_tag @listing.image, alt: @listing.title %> %>
      <%# <% else %> %>
        <%# <%= image_tag "/assets/images/loading.jpg", alt: @listing.title %> %>
      <%# <% end %> %>
    <%# </div> %>

  <div class="card-image">
  <figure class="image is-4by3">
    <% if listing.picture.attached? %>
    <%= link_to list_path(listing.id) do %>
    <%= image_tag listing.picture%>
    <%end%>
    <% else %>
    <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
    <% end %>

    <% @listings.each do |listing| %>
      <span>
        <h2><%= listing.title %></h2>
        <h5> Cusine: <%= listing.cuisine %> </h5>
        <h5><%= listing.description %></h5>
        <h5> Allergies: <%= listing.allergy.name %></h5>
        <h5> Date Available: <%= listing.available_date %></h5>
        <h5> Price: $<%= listing.price %></h5>
        <h5> Location for pickup: 
            <%= listing.user.address.suburb %>,
            <%= listing.user.address.postcode %></h5>
        <h2 ><%= link_to 'View this meal!', listing, class: "button button-primary"%></h2>
        <%# user see options of edit/destroy if they own the listing %>
        <% if current_user && current_user.id == listing.user_id %>
            <h2><%= link_to 'Edit', edit_listing_path(listing), class: "button" %></h2>
            <h2><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "button" %></h2>
        <% end %>
      </span>
    <% end %>
  </body>

app/views/shared/_nav.html.erb
<nav>
<%# logo on top left of nav bar %>
<%=image_tag('logo.png', class:"logo")%>

<%= link_to "Available Meals", listings_path, class: "button" %>
<%= link_to "About", root_path, class: "button" %>

<%= link_to "My Meals Claimed", orders_bought_path, class: "button" %>
<%= link_to "My Meals Sold/Donated", orders_sold_path, class: "button" %>

<span style="float: right">
    <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "button button-primary" %>
        <%= link_to "Update my profile", edit_user_registration_path, class: "button button-primary" %>
    <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "button button-primary" %>
        <%= link_to "Sign in", new_user_session_path, class: "button button-primary" %>
    <% end %>
    </span>
</nav>